[deps]: pin faraday at >= 1.0 and bump version
mikamai/onesignal-ruby pull request #25
Opened 2021-02-01 02:34 UTC by jongirard

In this PR I updated the faraday dependency to `~> 1.0` as previously it was pinned at a very old version and causing compatibility issues in my Gemfile with other gems.

2021-02-02 09:47 UTC, MatteoJoliveau commented
Hi @jongirard , thank you for this PR!
Since this is a major upgrade to Faraday, and to a 1.0 version no less, I wanna double check that the upgrade does not break anything for the end-users of the library.

Since the current testing infrastructure is a bit broken at the moment, I'll put this PR on hold. We'll get back to it as soon as we have proper pipelines back up 👍🏻

2021-03-01 23:31 UTC, jongirard commented
Sounds good 👍🏻 I can report that I have been using it at ~1.0 for a little while now without any issues so hopefully the tests go smoothly

2021-03-25 07:54 UTC, dmitry commented
@MatteoJoliveau any help required on this? In other case there are no possibility to upgrade faraday for the other gems, means other gems cannot be upgraded too.

2021-03-25 11:20 UTC, MatteoJoliveau commented
@dmitry we're working on it. We're fixing the CI pipelines to have PR checks back. Bear with us 🙏🏻 
In the meantime @jongirard can I as you to change the version to `0.5.0` instead of `0.4.1` since it's not a bugfix?

2021-05-14 18:52 UTC, MatteoJoliveau requested changes
Minor change to properly follow semver 👍🏻

2021-05-14 18:52 UTC, MatteoJoliveau commented on lib/onesignal/version.rb
> +  VERSION = '0.4.1'
```suggestion
  VERSION = '0.5.0'
```

2021-05-17 14:32 UTC, merged